services:
  - type: web
    name: discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENTID
        sync: false
      - key: GUILDID
        sync: false
